version: "3.8"

services:
  nodeserver:
    build:
      context: ./nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/usr/src/app
    networks:
      - node-challenge-network
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    depends_on:
      - db

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    networks:
      - node-challenge-network
    depends_on:
      - nodeserver

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-challenge-network        

networks:  
  node-challenge-network:
    driver: bridge
